-- AlterTable
ALTER TABLE "Station" ADD COLUMN     "aiResult" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "humanCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
